##{{ if .Values.addons.pidtooEnabled }}
apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: pidtoo-iris-application
      namespace: argocd
    spec:
      destination:
        namespace: isc
        server: https://kubernetes.default.svc
      project: default
      source:
        path: iko/iko/iris_operator_amd-3.8.42.100/samples
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true 
## { end }}